version: '3'

services:
  mailer:
    build: .
    container_name: mailer
    environment:
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASS=${MAILER_PASS}
      - MAILER_EMAIL_TO=${MAILER_EMAIL_TO}
      - MAILER_PORT=${MAILER_PORT:-25}
    ports:
      - 8080:80
    restart: unless-stopped
